language: c
dist: trusty
sudo: false
env:
  global:
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1

cache:
  directories:
    - $HOME/sdk
  ccache

before_script:
  - ./.travis_do.sh download_sdk

script:
  - ./.travis_do.sh test_packages
notifications:
  email: false
  webhooks: https://ambrosio-tele.herokuapp.com/sacarinobot/travisci/133188453
  on_success: always # default: always
  on_failure: always # default: always
  on_start: always   # default: never
